Remove pylint from build
Failing due to crazy error in container. Punting, again.

```
  File "/usr/local/lib/python3.5/functools.py", line 571, in _c3_merge
  151s
  734
      raise RuntimeError("Inconsistent hierarchy")
      151s
      735
      RuntimeError: Inconsistent hierarchy
      151s
      736
      make: *** [pylint] Error 1
```