Remove pylint from build due to odd weakref error
Error happens on buildserver

KeyError: <weakref at 0x7f4e845be458; to 'EnumMeta' at 0x12ce1e8 (Context)>
https://drone.cglcloud.com/DataPlatform/pipewrench/11